### ISSUE TITLE
Determine number of levels needed

### ISSUE THREAD

**Issue by rayrshah** [rayrshah/happy-apple#3]
We need 3+ levels:
Grade Level (K-1) > Exercise name (Invent a Wheel) > Submodules (step 1, 2, etc)
The template only allows 2 levels:
Header > Subheader

**Comment by rayrshah** [comment]
@myqntm what do you mean by this:
"I was thinking of creating separate 'doc' type pages for each grade level - will see if I can figure it out. "

**Comment by myqntm** [comment]
Here's essentially what I was trying to do (see menu in first screenshot below). A separate doc page for each grade (one for k-1, one for 2-3, etc) which we'd later organize as a parent called 'For Educators':

The issue though is that it seems it's only reading content from one of the sections so both k-1 and 1-2 are exactly the same. K-1 should say 'invent-a-wheel' and 1-2 should have 'about'.

<img width="841" alt="Screen Shot 2019-09-24 at 10 09 58 AM" src="https://user-images.githubusercontent.com/2772738/65529704-e096c400-deb3-11e9-93c8-4b8c08b354e3.png">

<img width="704" alt="Screen Shot 2019-09-24 at 10 10 12 AM" src="https://user-images.githubusercontent.com/2772738/65530531-62d3b800-deb5-11e9-93de-7f9874e78584.png">

**Comment by rayrshah** [comment]
Do you have time for a zoom?

**Comment by rayrshah** [comment]
This is fixed, no?

**Comment by myqntm** [comment]
Correcto.
