### ISSUE TITLE
Produce Sitemap

### ISSUE THREAD

**Issue by rayrshah** [rayrshah/happy-apple#4]

**Comment by rayrshah** [comment]
HI @myqntm here's the sitemap

https://app.rarchy.com/v/83125fb433bc

**Comment by rayrshah** [comment]
![image](https://user-images.githubusercontent.com/2479135/65721393-f81eaa00-e077-11e9-8a8f-5542b70e80d4.png)

**Comment by myqntm** [comment]
Fantastic. Thank you @rayrshah !

**Comment by rayrshah** [comment]
@myqntm there is a section missing in this IA: 

Extensions at the bottom of each unit. For example, **The Digital Multimeter** is the **Electrocity** extension

I may have missed more stuff. LMK if you spot any content that needs adding
